### ISSUE TITLE
Doesn't build on Windows with Zig 0.14.0

### ISSUE THREAD

**Issue by Arylen** [afterschoolstudio/Luau.NET#1]
Hey there, I'm trying to build this on Windows with Zig 0.14.0, and encountering some errors.

My Zig version is: `0.14.0-dev.2210+62f4a6b4d`

Attempting to run `zig build` in the `./build` folder results in:

```
F:\Cali\Luau.NET\build\build.zig:28:9: error: local variable is never mutated
    var luacode_api_flag = if (lib.target.isWindows()) "-DLUA_API=extern\"C\" __declspec(dllexport) " else "-DLUACODE_API=extern\"C\"";
        ^~~~~~~~~~~~~~~~
F:\Cali\Luau.NET\build\build.zig:28:9: note: consider using 'const'
F:\Cali\Luau.NET\build\build.zig:27:9: error: local variable is never mutated
    var lua_api_flag = if (lib.target.isWindows()) "-DLUA_API=extern\"C\" __declspec(dllexport) " else "-DLUA_API=extern\"C\"";
        ^~~~~~~~~~~~
F:\Cali\Luau.NET\build\build.zig:27:9: note: consider using 'const'
```

It appears that in Zig 0.12.0, not mutating `var` variable will result in an error until you change them to `const`'s, so I've changed them to `const` locally to get past this.

After that change, I am now running into:
```
F:\Cali\Luau.NET\build\build.zig:27:34: error: no field named 'target' in struct 'Build.Step.Compile'
    const lua_api_flag = if (lib.target.isWindows()) "-DLUA_API=extern\"C\" __declspec(dllexport) " else "-DLUA_API=extern\"C\"";
                                 ^~~~~~
C:\Tools\zig 0.14.0\lib\std\Build\Step\Compile.zig:1:1: note: struct declared here
```

Due to my unfamiliarity with either of these tools, I'm not really sure what the next thing to look at here would be and I'm hoping that I can get some help here if it's not too bothersome. I can submit a PR for the `var` -> `const` change, but would like to wait until after this if there are more changes required.

**Comment by kkukshtel** [comment]
Thanks for sending this over and trying to use the lib!

Zig is definitely changing a lot over time so its inevitable something would break here. TBH I barely knew enough Zig to get this working in the first place. I suspect it's something with how the build api is changing (maybe try `target.result.isWindows()`?) I'd say go ask in the discord how to migrate this script to use latest zig.

Otherwise potentially downgrade your zig install to the older release I used here.

One other option I'd also be open to is incorporating the msbuild-ified version of zig to this repo so there isn't a dep on a local zig install but instead you get it "for free" with the repo. https://github.com/vezel-dev/zig-sdk

**Comment by 177unneh** [comment]
I also get that error. What version of zig version have you used to make it work in the first place?

**Comment by 177unneh** [comment]
Ok so i figured. 
You need to have zig 10.
Also the LUAU here is outated.. it does not have buffer element!

**Comment by kkukshtel** [comment]
@177unneh Feel free to submit a PR here for Zig/Luau version updates! I haven't really touched this project since the initial spike so happy to accept things as trivial modern zig compat upgrades/Luau submodule version bumps.
